### PR TITLE
Send location data to analytics.page

### PR DESCRIPTION
**Pull request by mickeyreiss-visor**

### CODE REVIEW

**Comment by stephenmathieson** [comment]
I'm not sure this is necessary, as analytics.js includes these properties by default.

From the [documentation](https://segment.com/docs/sources/website/analytics.js/#page):

> [...] url, title, referrer and path are collected automatically! Additionally this defaults to a canonical url, if available, and falls back to document.location.href.

**Comment by mickeyreiss-visor** [comment]
Good point. I will reopen if this ends up a problem.

**Comment by mickeyreiss-visor** [comment]
@stephenmathieson based on my production data, I think this PR (or something similar) will be necessary. All of my events are coming through with `path: '/'`. This is true both for direct page loads, as well as gatsby-link navigation.

Here's a screenshot of my Segment debugger, filtered down to my session ID as I click around my Gatsby site:

image

**Comment by stephenmathieson** [comment]
Somehow just saw this notification. I'll look into this now

**Comment by stephenmathieson** [comment]
Hmm, everything seems fine to me. Here's a screenshot of running the example in production mode:

image

Also, I just invited you to my ["gatsby_segment_plugin" source](https://app.segment.com/stephenmathieson/sources/gatbsy_segment_plugin/debugger) so you can poke around in the debugger. If you run the example on your own, do you see `/foo` page calls coming in?

**Comment by mickeyreiss-visor** [comment]
Hey @stephenmathieson I tried your example and it is working for me as expected. But, I did find the issue thanks to your work..

As it turns out, the root was an unexpected interaction between analytics.js and canonical Link tags.

[From analytics.js:](https://github.com/segmentio/analytics.js/blob/b237600d802e8d1afda7e7a27baec5998fc05471/analytics.js#L6513-L6518)

```js
function canonicalPath() {
  var canon = canonical();
  if (!canon) return window.location.pathname;
  var parsed = url.parse(canon);
  return parsed.pathname;
}
```

This means that `<Link rel="canonical" >` takes precedent when inferring the `page` payload. 

In my Gatsby app, canonical link tag had a bug. It was incorrectly hard-coded to the my home page. Therefore, this plugin was reporting `/` as the path for all pages. 

When I switched to `gatsby-plugin-canonical-link`, I realized that ordering was critical. `gatsby-plugin-segment` needs to be listed _after_ `gatsby-plugin-canonical-link` in `gatsby-node.js`. Otherwise, analytics events will be sent for the last browser location. (Maybe gatsby-plugin-segment could work around this somehow?)

Anyway, I don't think there is an issue with gatsby-plugin-segment. Just a few subtleties in the interactions between this plugin, Gatsby and Segment.

**Comment by stephenmathieson** [comment]
Ahh, yep, that'd do it!

Glad you figured this out! Let me know if anything else comes up =]

**Pull request closed without merging**
